### ISSUE TITLE
Support for the latest generation of UniFi Access hubs

### ISSUE THREAD

**Issue by hakt0-r** [hjdhjd/homebridge-unifi-access#10]
### Homebridge UniFi Access Version

v1.2.2

### Homebridge Platform and OS

Synology DSM

### Homebridge Version

v1.7.0

### Node Version

v20.9.0

### UniFi OS Version

v3.2.12

### UniFi Access Controller Version

v1.24.7

### Describe the problem

So I've got a simple setup, all brand new and just trying to make things work please.
- I've got a UDM PRO SE, 192.168.1.27, version details are all above. 
- I've got the latest UA-G2-PRO starter kit, with the camera and the touch screen at the front door of my house.
- I've got a Yale + level lock
- We are a homeKit home.

My intention is for one of us to come home, use one of the many ways to unlock the door and trigger the homeKit automation to unlock our Yale and Level Locks. 

I've installed this fresh as per the instructions, even given it its own child Bridge, but when I try to add it to out home in the homeKit, it shows the message, unable to add accessory, accessory is NOT rechable. 

### Homebridge HBUA JSON configuration

```json
{
    "controllers": [
        {
            "address": "192.168.1.27",
            "name": "Gandalf",
            "password": "password123_notReally=)",
            "username": "hbGandalf"
        }
    ],
    "name": "UniFi Access",
    "_bridge": {
        "username": "0E:9F:64:33:A4:EE",
        "port": 38937
    },
    "platform": "UniFi Access"
}
```

### Relevant log output

```shell
(node:18011) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.

(Use `node --trace-deprecation ...` to show where the warning was created)

[4/20/2024, 8:39:13 AM] [UniFi Access] UDM: Connected to 192.168.1.27 (UniFi Access v1.24.7+5199 running on UniFi OS 3.2.12).

[4/20/2024, 8:39:13 AM] [UniFi Access] UDM: Discovered UA Hub Door: UA-HUB-DOOR-B11E [UA Hub Door] (address: 192.168.1.74 mac: F4E2C6B1B11E).

[4/20/2024, 8:39:13 AM] [UniFi Access] UDM: Discovered UA G2 Pro: UA-G2-PRO-3EA3 [UA G2 Pro] (address: 192.168.1.213 mac: F4E2C6B13EA3).

[4/20/2024, 8:39:13 AM] [UniFi Access] UDM: UniFi Access device type 'UAH-DOOR' is not currently supported, ignoring: UA-HUB-DOOR-B11E [UA Hub Door].

[4/20/2024, 8:39:13 AM] [UniFi Access] UDM: UniFi Access device type 'UA-G2-PRO' is not currently supported, ignoring: UA-G2-PRO-3EA3 [UA G2 Pro].
```

### Acknowledgment that you are only running UniFi OS and UniFi Access releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
Thanks for the report. Please try v1.3.0 that I just released and confirm that it works. 😄

**Comment by hakt0-r** [comment]
You are a legend! It works perfectly. Thanks mate.
