### ISSUE TITLE
Unifi Access Hub does not open the lock

### ISSUE THREAD

**Issue by ShadowD** [hjdhjd/homebridge-unifi-access#12]
### Homebridge UniFi Access Version

v1.3.0

### Homebridge Platform and OS

Homebridge on Synology Disc Station

### Homebridge Version

1.8.2

### Node Version

v20.9.0

### UniFi OS Version

3.2.12

### UniFi Access Controller Version

2.0.6

### Describe the problem

* G2 Reader Pro
* Access Hube New Gen

Issue - when I try to open the lock, the button jumps to open, but the lock itself never opens.

I also have an additional question, do you plan to add support for the reader's intercom?

### Homebridge HBUA JSON configuration

```json
{
    "bridge": {
        "name": "Homebridge 1111",
        "username": "11:11:11:11:11:11",
        "port": 51657,
        "pin": "111-11-111",
        "advertiser": "avahi"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "controllers": [
                {
                    "address": "192.168.0.1",
                    "password": "1111111111111",
                    "username": "HomeBridge"
                }
            ],
            "name": "UniFi Access",
            "platform": "UniFi Access",
            "options": [
                "Enable.Device.SyncName.D8B37093C7A0"
            ]
        },
        {
            "controllers": [
                {
                    "address": "192.168.0.1",
                    "username": "HomeBridge",
                    "password": "11111111111"
                }
            ],
            "name": "UniFi Protect",
            "platform": "UniFi Protect"
        }
    ],
    "disabledPlugins": []
}
```

### Relevant log output

```shell
[6/4/2024, 12:34:42 AM] [UniFi Access] Ssssssssssss-111 UA-HUB-DOOR-C7A0 [UA Hub Door]: Unable to unlock.
[6/4/2024, 12:34:43 AM] [UniFi Access] Ssssssssssss-111 UA-HUB-DOOR-C7A0 [UA Hub Door]: Unable to unlock.
```

### Acknowledgment that you are only running UniFi OS and UniFi Access releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
Thanks for the report. Did this work previously and stop working, or is this a new install?

**Comment by ShadowD** [comment]
Hi, this is new installation.

**Comment by larstobi** [comment]
I have the same issue. But the issue also occurs when I try to open via the Access app on my iPhone, and also when using the keypad. This leads me to believe there is a software issue with Unifi.

**Comment by ShadowD** [comment]
For me it works normally through the native Unifi Access application.

**Comment by larstobi** [comment]
I checked the output terminals for the strike lock from the Access Hub, and the multimeter showed 12V correctly, but the lock still didn't open. I have submitted an RMA to Ubiquiti about the electric strike lock. It could be defective.

**Comment by ShadowD** [comment]
Unfortunately it still doesn't work for me ;-(

**Comment by larstobi** [comment]
I got my R.M.A. replacement lock yesterday and so far I have 100% success unlocking.
