### ISSUE TITLE
UA Ultra not supported

### ISSUE THREAD

**Issue by zoic21** [hjdhjd/homebridge-unifi-access#14]
### Homebridge UniFi Access Version

v1.3.0

### Homebridge Platform and OS

Docker synology

### Homebridge Version

v1.8.3

### Node Version

v20.15.0

### UniFi OS Version

4.0.6

### UniFi Access Controller Version

2.1.2

### Describe the problem

Device UA-ULTRA not supported (https://eu.store.ui.com/eu/en/pro/category/all-door-access/products/ua-ultra).

### Homebridge HBUA JSON configuration

```json
{
    "controllers": [
        {
            "address": "XXXX",
            "password": "XXXX",
            "username": "XXXX"
        }
    ],
    "name": "UniFi Access",
    "options": [
        "Disable.Hub.Doorbell.X",
        "Disable.Log.Doorbell.X",
        "Enable.Hub.Lock.Trigger.X"
    ],
    "_bridge": {
        "username": "XX:XX:XX:XX:XX:XX",
        "port": XXXX
    },
    "platform": "UniFi Access"
}
```

### Relevant log output

```shell
UNVR: UniFi Access device type 'UA-ULTRA' is not currently supported, ignoring: UA Ultra c4ad [UA Ultra].
```

### Acknowledgment that you are only running UniFi OS and UniFi Access releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
Thanks, this will be supported in a future release.
