### ISSUE TITLE
Issue with UA-ULTRA

### ISSUE THREAD

**Issue by zoic21** [hjdhjd/homebridge-unifi-access#19]
### Homebridge UniFi Access Version

1.4.0

### Homebridge Platform and OS

Docker sinology

### Homebridge Version

v1.8.3

### Node Version

v20.15.0

### UniFi OS Version

4.0.6

### UniFi Access Controller Version

2.1.5

### Describe the problem

Hello, thanks for this new version but I have an issue with UA-ULTRA not well detected. Display as Not manage in Apple home application

### Homebridge HBUA JSON configuration

```json
{
    "controllers": [
        {
            "address": "XXXX",
            "password": "XXXX",
            "username": "XXXX"
        }
    ],
    "name": "UniFi Access",
    "options": [
        "Disable.Hub.Doorbell.X",
        "Disable.Log.Doorbell.X",
        "Enable.Hub.Lock.Trigger.X"
    ],
    "_bridge": {
        "username": "XX:XX:XX:XX:XX:XX",
        "port": XXXX
    },
    "platform": "UniFi Access"
}
```

### Relevant log output

```shell
[8/6/2024, 7:48:19 PM] [UniFi Access] UNVR: Connected to 192.168.1.235 (UniFi Access v2.1.5+6367 running on UniFi OS 4.0.6).
[8/6/2024, 7:48:19 PM] [UniFi Access] UNVR: Discovered UA Ultra: UA Ultra c4ad [UA Ultra] (address: 192.168.1.181 mac: 9CXXXXXXXXX).
[8/6/2024, 7:48:19 PM] [UniFi Access] UNVR: UNVR UA Ultra c4ad [UA Ultra]: Adding undefined to HomeKit.
[8/6/2024, 7:48:19 PM] [UniFi Access] UNVR: Unknown device class UA-ULTRA detected for UA Ultra c4ad.
```

### Acknowledgment that you are only running UniFi OS and UniFi Access releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
Thanks, appreciate you raising it to my attention.

**Comment by iFr0z3n** [comment]
Installed the plugin today for Access with UA Ultra, iI'm experiencing the same issue as zoic21
Device in HomeKit shows up, but states as "Not Supported"

**Comment by hjdhjd** [comment]
> Installed the plugin today for Access with UA Ultra, iI'm experiencing the same issue as zoic21 Device in HomeKit shows up, but states as "Not Supported"

Kindly do not post “me too” comments. You can thumbs up the issue. Managing support is difficult enough already 😄
