### ISSUE TITLE
 'UA-G2-PRO' & 'UA-G2-MINI' is not currently supported

### ISSUE THREAD

**Issue by peterxxl** [hjdhjd/homebridge-unifi-access#21]
### Describe the feature request

First time using this plugin... opening the door works fine, doorbell not so much, probably because of the following error in the log.

UniFi Access device type 'UA-G2-PRO' is not currently supported, ignoring: UA G2 Pro 9cbe [UA G2 Pro].
UniFi Access device type 'UA-G2-MINI' is not currently supported, ignoring: UA-G2-87C9 [UA G2].

### Describe the proposed solution

Add support if possible , please

### Describe alternatives you have considered to the enhancement

none

**Comment by hjdhjd** [comment]
This isn’t a productive report.
