### ISSUE TITLE
Support for UA-Intercom

### ISSUE THREAD

**Issue by joshuamanns** [hjdhjd/homebridge-unifi-access#23]
### Describe the feature request

I've seen the other issues referencing support for this device, and saw that it is not currently a priority for development. I do believe this device is picking up adoption quickly and users (including me :-)) would benefit from support Intercom as it is intended to work directly with the access hub.

### Describe the proposed solution

Add support for UA-Intercom with the Access Hub in this plugin.

### Describe alternatives you have considered to the enhancement

Add support for the UA-Intercom camera within the Protect plugin or just as another camera source in HK.

**Comment by hjdhjd** [comment]
Please read prior issues before spamming with new ones. :smile:

#20
