### ISSUE TITLE
UA Ultra Support?

### ISSUE THREAD

**Issue by willymoyer** [hjdhjd/homebridge-unifi-access#26]
### Homebridge UniFi Access Version

1.5.0

### Homebridge Platform and OS

Mac mini, Debian GNU/Linux Bookworm (12)

### Homebridge Version

v4.61.0

### Node Version

v18.20.4

### UniFi OS Version

v4.0.20

### UniFi Access Controller Version

2.3.20

### Describe the problem

Unable to unlock new UA Ultra with homebridge, just says not supported.

### Homebridge HBUA JSON configuration

```json
{
    "controllers": [
        {
            "address": "192.168.1.1",
            "password": "XXXX",
            "username": "XXXX"
        }
    ],
    "name": "UniFi Access",
    "_bridge": {
        "username": "0E:22:ED:XX:XX:XX",
        "port": 42093
    },
    "platform": "UniFi Access"
}
```

### Relevant log output

```shell
Unknown device class UA-ULTRA detected for Will’s Office Door.
```

### Acknowledgment that you are only running UniFi OS and UniFi Access releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
Coming in the future. Thanks for the report
