### ISSUE TITLE
UA-Intercom - Support ?

### ISSUE THREAD

**Issue by daveneill** [hjdhjd/homebridge-unifi-access#27]
### Describe the feature request

We currently use the Unifi Doorbell Pro on Protect to integrate with HomeKit with full camera and doorbell support but request the access to include the Unifi UA-Intercom full support not just the doorbell and lock support.

### Describe the proposed solution

We currently use the Unifi Doorbell Pro on Protect to integrate with HomeKit with full camera and doorbell support but request the access to include the Unifi UA-Intercom full support not just the doorbell and lock support.

### Describe alternatives you have considered to the enhancement

We currently use the Unifi Doorbell Pro on Protect to integrate with HomeKit with full camera and doorbell support but request the access to include the Unifi UA-Intercom full support not just the doorbell and lock support.

**Comment by hjdhjd** [comment]
PRs welcome, but no immediate plans to support this myself. Thanks for the request.
