### ISSUE TITLE
Bridge UniFi Access and Ring Alarm?

### ISSUE THREAD

**Issue by jleimantest** [hjdhjd/homebridge-unifi-access#29]
### Homebridge UniFi Access Version

1.5.0

### Homebridge Platform and OS

macOS Sequoia

### Homebridge Version

1.85

### Node Version

20.18.0

### UniFi OS Version

4.0.20

### UniFi Access Controller Version

2.5.2

### Describe the problem

I'm trying to connect UniFi Intercom and Ring Alarm:

1. User unlocks a door by authenticating with the UniFi Intercom (key fob, access card, etc)
2. Ring Alarm is set to Home (off)

In theory, could I use this plugin to detect an unlock event and write a HomeKit automation to set the Ring Alarm to Home?

### Homebridge HBUA JSON configuration

```json
This is a theory - do not have the setup installed yet.
```

### Relevant log output

```shell
This is a theory - do not have the setup installed yet.
```

### Acknowledgment that you are only running UniFi OS and UniFi Access releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
Sorry, as I don’t use nor support Ring anything there’s not much I can answer here. I’d suggest you try the Homebridge discord potentially. Nothing stops you from automating activities, but Apple is particular about what you can do unattended for accessories it considers security related. Best of luck!

**Comment by jleimantest** [comment]
Totally understood. Thanks!
