### ISSUE TITLE
feature request: Cameras and HomeKit unlock support

### ISSUE THREAD

**Issue by ydnar** [hjdhjd/homebridge-unifi-access#7]
### Describe the feature request

Hi there, thanks for writing this and the Protect plugin. They’re fantastic. I was wondering about two features, whether they’re on your roadmap:

1. Camera support from Access readers
2. Mapping unlock events to a separate lock exposed in HomeKit

Thanks!

### Describe the proposed solution

1. Camera support akin to your UniFi Protect plugin
2. Unlock events from the Access Hub can trigger other locks in HomeKit

### Describe alternatives you have considered to the enhancement

Not sure.

**Comment by hjdhjd** [comment]
1. This is on my roadmap, but unlikely to happen anytime soon. Access is an entirely different beast from Protect and getting video from Access is a very different proposition currently. Access uses webrtc for video which creates a whole different set of challenges. Access is not a pretty API on a number of fronts.
2. I have no plans to implement anything like this. My plugins, as you know, tend to focus on one thing really well - first-class HomeKit support for the platform I take on. You can always create a HomeKit automation to do what you’re looking for.

**Comment by ydnar** [comment]
Thanks, I looked and didn't see documentation for anything that would fire a HomeKit button or trigger when a user unlocks the door with a key fob or card (or PIN). Does that exist?

**Comment by hjdhjd** [comment]
See the MQTT support for this plugin, and look at the Homebridge MQTTthing plugin. In thinking about it a bit more, I may add an additional automation switch specifically for the lock in the next release.

Thanks for the suggestions.
